### PR TITLE
Fix #7: build's long path issue

### LINKED ISSUE #7: Builds fails
I noticed the builds haven been failing for 2 days. I tried building on my local machine and everything seemed fine though. I wonder what the cause is.

### PR DESCRIPTION
**Pull request by vinhphm**
This should fix the long path issue in #7 by enable long path setting in Git and Windows.

### CODE REVIEW

**Comment by LucasFA** [comment]
@vinhphm just FYI, all commits that you push to this branch show in this PR. You know, in case you want to consider using a different branch in your repo. Thanks for fixing this!

**Comment by vinhphm** [comment]
@LucasFA, my initial thought was to not actively maintain another repo and to delete the repo right away when merged, but I guess it couldn’t hurt to have one in preparation, so I will close this one for now.

**Comment by LucasFA** [comment]
That works, cool. It really was just an FYI, I didn't mean for you to close the PR or anything.

**Comment by deevus** [comment]
Thanks for this @vinhphm 

Fixed in #9

**Pull request closed without merging**
